import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b1e38",
  },
  topBar: {
    height: 92,
    justifyContent: "center",
    paddingHorizontal: 22,
    paddingTop: 16,
    backgroundColor: "#0c243f",
    borderBottomLeftRadius: 28,
  },
  backButton: {
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  contentContainer: {
    flex: 1,
    marginTop: -14,
    backgroundColor: "#f4f4f4",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 100,
  },
  title: {
    color: "#0B233E",
    fontSize: 26,
    fontWeight: "800",
    marginTop: 22,
    marginBottom: 18,
    letterSpacing: 0.2,
  },
  addCard: {
    backgroundColor: "#E8E8E8",
    borderRadius: 14,
    minHeight: 150,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 18,
  },
  addText: {
    color: "#0B233E",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 10,
  },
  plusCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 3,
    borderColor: "#0B233E",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E8E8E8",
  },
  sectionTitle: {
    color: "#0B233E",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 26,
    marginBottom: 12,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D9D9D9",
    borderRadius: 18,
    height: 52,
    paddingHorizontal: 12,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 52,
    color: "#1A1A1A",
    fontSize: 18,
  },
  listContainer: {
    marginTop: 38,
    gap: 12,
  },
  eventItem: {
    backgroundColor: "#D9D9D9",
    borderRadius: 12,
    height: 52,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  eventText: {
    color: "#0B233E",
    fontSize: 17,
    fontWeight: "700",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.38)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#E4E4E4",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 18,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  modalTitle: {
    color: "#0B233E",
    fontSize: 24,
    fontWeight: "800",
  },
  closeButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    backgroundColor: "#E6E6E6",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#BFC6CF",
    height: 46,
    paddingHorizontal: 12,
    color: "#0B233E",
    fontSize: 16,
    marginBottom: 12,
  },
  dateButton: {
    backgroundColor: "#E6E6E6",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#BFC6CF",
    height: 46,
    paddingHorizontal: 12,
    justifyContent: "center",
    marginBottom: 12,
  },
  dateButtonText: {
    color: "#0B233E",
    fontSize: 16,
  },
  previewImage: {
    width: "100%",
    height: 140,
    borderRadius: 10,
    backgroundColor: "#DADADA",
    marginBottom: 12,
  },
  modalActions: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#0c243f",
    borderRadius: 12,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "800",
  },
  iconButton: {
    width: 58,
    height: 52,
    borderRadius: 12,
    backgroundColor: "#0c243f",
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;
